In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sb
import warnings as wr
wr.filterwarnings('ignore')

In [2]:
df_voice=pd.read_csv('voice-classification.csv')

In [3]:
df_voice.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [4]:
df_voice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   obje

In [5]:
# check the basic distribution of the data
df_voice.describe().T

count       mean         std       min       25%       50%  \
meanfreq  3168.0   0.180907    0.029918  0.039363  0.163662  0.184838   
sd        3168.0   0.057126    0.016652  0.018363  0.041954  0.059155   
median    3168.0   0.185621    0.036360  0.010975  0.169593  0.190032   
Q25       3168.0   0.140456    0.048680  0.000229  0.111087  0.140286   
Q75       3168.0   0.224765    0.023639  0.042946  0.208747  0.225684   
IQR       3168.0   0.084309    0.042783  0.014558  0.042560  0.094280   
skew      3168.0   3.140168    4.240529  0.141735  1.649569  2.197101   
kurt      3168.0  36.568461  134.928661  2.068455  5.669547  8.318463   
sp.ent    3168.0   0.895127    0.044980  0.738651  0.861811  0.901767   
sfm       3168.0   0.408216    0.177521  0.036876  0.258041  0.396335   
mode      3168.0   0.165282    0.077203  0.000000  0.118016  0.186599   
centroid  3168.0   0.180907    0.029918  0.039363  0.163662  0.184838   
meanfun   3168.0   0.142807    0.032304  0.055565  0.116998  0.140519   
minfun    3168.0   0.036802    0.019220  0.009775  0.018223  0.046110   
maxfun    3168.0   0.258842    0.030077  0.103093  0.253968  0.271186   
meandom   3168.0   0.829211    0.525205  0.007812  0.419828  0.765795   
mindom    3168.0   0.052647    0.063299  0.004883  0.007812  0.023438   
maxdom    3168.0   5.047277    3.521157  0.007812  2.070312  4.992188   
dfrange   3168.0   4.994630    3.520039  0.000000  2.044922  4.945312   
modindx   3168.0   0.173752    0.119454  0.000000  0.099766  0.139357   

                75%          max  
meanfreq   0.199146     0.251124  
sd         0.067020     0.115273  
median     0.210618     0.261224  
Q25        0.175939     0.247347  
Q75        0.243660     0.273469  
IQR        0.114175     0.252225  
skew       2.931694    34.725453  
kurt      13.648905  1309.612887  
sp.ent     0.928713     0.981997  
sfm        0.533676     0.842936  
mode       0.221104     0.280000  
centroid   0.199146     0.251124  
meanfun    0.169581     0.237636  
minfun     0.047904     0.204082  
maxfun     0.277457     0.279114  
meandom    1.177166     2.957682  
mindom     0.070312     0.458984  
maxdom     7.007812    21.867188  
dfrange    6.992188    21.843750  
modindx    0.209183     0.932374

In [6]:
df_voice.isna().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [7]:
df_voice.shape

(3168, 21)

In [8]:
# total no of cadidates
df_voice.shape[0]

3168

In [9]:
# No. of Male candidates
df_voice[df_voice['label']=='male'].shape[0]

1584

In [10]:
# No. of Female candidates
df_voice[df_voice['label']=='female'].shape[0]

1584

In [11]:
df_voice['label'].value_counts()

male      1584
female    1584
Name: label, dtype: int64

In [12]:
# assign featues to x axis & target to y axis
x_features=df_voice.drop(['label'],axis=1)
y_target=df_voice['label']

In [13]:
# apply Label encoding to convert the target variables from categorical to numerical
from sklearn.preprocessing import LabelEncoder

In [14]:
gender_encoder=LabelEncoder()

In [15]:
y_target=gender_encoder.fit_transform(y_target)

In [16]:
gender_encoder.classes_

array(['female', 'male'], dtype=object)

In [20]:
y_target

array([1, 1, 1, ..., 0, 0, 0])

In [21]:
# Train Test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_features,y_target,test_size=0.3,random_state=123)

In [22]:
# scale the features
from sklearn.preprocessing import StandardScaler

In [23]:
# instantiate the object
scaler=StandardScaler()

In [25]:
# scale both training & testing datasets
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

## Support Vector Classifier

In [26]:
# Train a model
from sklearn.svm import SVC

In [27]:
# create a model
svc_model=SVC()

In [28]:
# train the model
svc_model.fit(x_train,y_train)

SVC()

In [29]:
# predict the training dataset
y_train_pred=svc_model.predict(x_train)

In [30]:
y_train_pred

array([0, 1, 1, ..., 0, 1, 1])

In [31]:
# check the no. of features x train has taken
svc_model.n_features_in_

20

In [32]:
# predict the test dataset
y_test_pred=svc_model.predict(x_test)

In [35]:
y_test_pred[0:5]

array([1, 0, 0, 1, 1])

In [36]:
# check the accuracy
from sklearn.metrics import accuracy_score, confusion_matrix

In [37]:
# check the accuracy of the training dataset
acc_train=accuracy_score(y_train_pred,y_train)
acc_train

0.986468200270636

In [38]:
cm_train=confusion_matrix(y_train_pred,y_train)
cm_train

array([[1082,   16],
       [  14, 1105]], dtype=int64)

In [39]:
# check the accuracy of the testing dataset
acc_test=accuracy_score(y_test_pred,y_test)
acc_test

0.9768664563617245

In [40]:
cm_test=confusion_matrix(y_test_pred,y_test)
cm_test

array([[476,  10],
       [ 12, 453]], dtype=int64)

In [41]:
# we are satisfied with these results in real life because the data set is quite small, 
# but for the sake of practice we are using Decision Tree, Random Forest, GridSearch Cross validation

## Decision Tree

In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
dtree=DecisionTreeClassifier()

In [44]:
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [45]:
# predict the training dataset
y_train_pred_dt=dtree.predict(x_train)

In [46]:
acc_train_dt=accuracy_score(y_train_pred_dt,y_train)
acc_train_dt

1.0

In [47]:
# predict the testing dataset
y_test_pred_dt=dtree.predict(x_test)

In [48]:
acc_test_dt=accuracy_score(y_test_pred_dt,y_test)
acc_test_dt

0.9663512092534174

## Random Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
RFC=RandomForestClassifier()

In [51]:
RFC.fit(x_train,y_train)

RandomForestClassifier()

In [52]:
# predict training set
y_train_pred_rf=RFC.predict(x_train)

In [53]:
acc_train_rf=accuracy_score(y_train_pred_rf,y_train)
acc_train_rf

1.0

In [54]:
# predict testing set
y_test_pred_rf=RFC.predict(x_test)

In [55]:
acc_test_rf=accuracy_score(y_test_pred_rf,y_test)
acc_test_rf

0.9747634069400631

## Gridsearch Cross Validation

In [57]:
# Create a dictionary called param_grid and fill out some parameters for C and gamma
param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1,0.1,0.01,0.001,0.0001]}

In [58]:
# import Gridsearch CV class
from sklearn.model_selection import GridSearchCV

In [59]:
# instantiate an object of the class
grid=GridSearchCV(SVC(),param_grid,refit=True,verbose=2)

### K Fold Cross Validation-----> splits the model into training & testing sets (here k=5), it loops across the k fold & splits the data into (k-1) for training set & 1 for testing

In [60]:
# fit the model with training data
grid.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END .....................................C=0.1, gamma=1; total time=   0.4s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ..................................C=0.1, gamma=0.01; total time=   0.1s
[CV] END ..................................C=0.

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             verbose=2)

In [62]:
# predict the training & Testing data
y_train_pred_gs=grid.predict(x_train)
y_test_pred_gs=grid.predict(x_test)

In [63]:
# check accuracy
acc_train_gs=accuracy_score(y_train_pred_gs,y_train)
acc_test_gs=accuracy_score(y_test_pred_gs,y_test)

In [64]:
acc_train_gs

0.9900766801984664

In [65]:
acc_test_gs

0.9800210304942166

In [66]:
# confusion matrix
cm_train_gs=confusion_matrix(y_train_pred_gs,y_train)
cm_test_gs=confusion_matrix(y_test_pred_gs,y_test)

In [67]:
cm_train_gs

array([[1088,   14],
       [   8, 1107]], dtype=int64)

In [68]:
cm_test_gs

array([[478,   9],
       [ 10, 454]], dtype=int64)

In [70]:
# see the best parameters of grid model
grid.get_params()

{'cv': None,
 'error_score': nan,
 'estimator__C': 1.0,
 'estimator__break_ties': False,
 'estimator__cache_size': 200,
 'estimator__class_weight': None,
 'estimator__coef0': 0.0,
 'estimator__decision_function_shape': 'ovr',
 'estimator__degree': 3,
 'estimator__gamma': 'scale',
 'estimator__kernel': 'rbf',
 'estimator__max_iter': -1,
 'estimator__probability': False,
 'estimator__random_state': None,
 'estimator__shrinking': True,
 'estimator__tol': 0.001,
 'estimator__verbose': False,
 'estimator': SVC(),
 'n_jobs': None,
 'param_grid': {'C': [0.1, 1, 10, 100],
  'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': None,
 'verbose': 2}

## Alternatively (Not using Gridsearch) we can check the accuracy in the following way

In [71]:
# Create a dictionary called param_grid and fill out some parameters for C and gamma
param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1,0.1,0.01,0.001,0.0001]}

In [74]:
# fit the model & check the accurcy with (C=0.1, gamma=1)
model1 = SVC(C=0.1, gamma=1).fit(x_train,y_train)
accuracy_score(y_true= y_test, y_pred = model1.predict(x_test))

0.7981072555205048

In [75]:
# fit the model & check the accurcy with (C=0.1, gamma=0.1)
model2 = SVC(C=0.1,gamma=0.1).fit(x_train,y_train)
accuracy_score(y_true= y_test, y_pred = model2.predict(x_test))

0.9631966351209253

In [76]:
# to know which combination will be best we use an iterative method
accuracy = []
for c1 in [0.1,1, 10, 100]:
    for g1 in [1,0.1,0.01,0.001,0.0001]:
        model = SVC(C=c1, gamma = g1).fit(x_train,y_train)
        accuracy.append(accuracy_score(y_true= y_test, y_pred = model.predict(x_test)))

In [77]:
accuracy

[0.7981072555205048,
 0.9631966351209253,
 0.9495268138801262,
 0.8717139852786541,
 0.4868559411146162,
 0.9705573080967402,
 0.9800210304942166,
 0.9684542586750788,
 0.9516298633017876,
 0.8759200841219769,
 0.9705573080967402,
 0.9810725552050473,
 0.9726603575184016,
 0.964248159831756,
 0.9495268138801262,
 0.9705573080967402,
 0.9789695057833859,
 0.9768664563617245,
 0.9695057833859095,
 0.9674027339642481]

In [78]:
# c=10 & gamma=0.1 is the best values of the parameters
# fit the model & check the accurcy with (C=10, gamma=0.1)
model3 = SVC(C=10,gamma=0.1).fit(x_train,y_train)
accuracy_score(y_true= y_test, y_pred = model3.predict(x_test))

0.9810725552050473